### PR TITLE
Notify ChoiceSetManager of failed preloads

### LINKED ISSUE #1715: Choices not saved as preloaded if some choices fail
### Bug Report
The ChoiceSetManager currently only saves preloaded choices if all choices succeed in the PreloadChoicesOperation.
If any choices fail then the choices are not saved. We need to still save any successfully uploaded choices to avoid reuploading them in the future.

### PR DESCRIPTION
**Pull request by RHenigan**
Fixes #1715 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
- [X] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [X] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android, Java SE, and Java EE

#### Unit Tests
N/A

#### Core Tests
To test this fix I had to update the preloadCells() method in the PreloadChoicesOperation. 

```
private void preloadCells() {
        isRunning = true;
        final List<CreateInteractionChoiceSet> choiceRPCs = new ArrayList<>(cellsToUpload.size());
        for (ChoiceCell cell : cellsToUpload) {
            CreateInteractionChoiceSet csCell = choiceFromCell(cell);
            if (csCell != null) {
                if(choiceRPCs.size() == 0) {
                    csCell.getChoiceSet().get(0).setMenuName(null);
                }
                choiceRPCs.add(csCell);
            }
        }
```

This will set the menuName of the first csCell to null so it is forced to fail. Now you can debug the preloadChoices method of the BaseChoiceSetManager in the PreloadChoicesOperation onComplete listener you should observe that the preloadedChoices and pendingPreloadChoices arrays is uploaded with the correct choice cells.

### Summary
This PR adds a new ChoiceSetCompletionListener to be used by the PreloadChoicesOperation. In the even that choices fail to preload the new listener is used to notify the BaseChoiceSetManager which choice cells failed to preload.Any choice cells that were successfull will be added to the preloadedChoices and removed from the pendingPreloadChoices.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by JulianKast — COMMENTED** [review]
So if some choices fail to upload while others are successful, when they go to present that choiceSet, should the choices that successfully uploaded be presented?

**Comment by RHenigan** [comment]
@JulianKast If you try to present a list that requires preloads and some of those preloads failed then the entire present should fail. In the event that a choice set has "Yes" and "No" but yes fails to preload, we do not want to present just "no".

**Review by JulianKast — APPROVED** [review]

File: base/src/main/java/com/smartdevicelink/managers/ChoiceSetCompletionListener.java [hunk 1]
```diff
@@ -0,0 +1,16 @@
+package com.smartdevicelink.managers;
+
+import com.smartdevicelink.managers.screen.choiceset.ChoiceCell;
+
+import java.util.HashSet;
+
+public interface ChoiceSetCompletionListener {
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/ChoiceSetCompletionListener.java:7]: Can you make this a part of BaseChoiceSetManager like AlertSoftButtonClearListener in BaseAlertManager?

**Review by JulianKast — CHANGES_REQUESTED** [review]

**Review by JulianKast — APPROVED** [review]
