### PR TITLE
Bugfix/issue 1385

### LINKED ISSUE #1385: AndroidTestCase is not available on Android 28 and AndroidJUnit4 should be used instead
### Bug Report
`android.test.AndroidTestCase` is no longer available on Android 28. So tests need to be rewritten to work using annotations:

```
@RunWith(AndroidJUnit4.class)
public class ExampleInstrumentedTest {
    @Test
    public void test1() {
    }
}
```

### PR DESCRIPTION
**Pull request by RHenigan**
Fixes #1385

This PR is **[ready]** for review.

### Risk
This PR makes **[no]** API changes.

### Testing Plan
- [X] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [X] I have run the unit tests with this PR

#### Summary
AndroidTestCase is not available on Android 28 and AndroidJUnit4 should be used instead.
All classes that extended AndroidTestCase2 have been refactored to run with AndroidJUnit4.
BaseRPCTest is a parent class for many other test classes that also needed to be refactored to use the JUnit framework.
RSVTestCase and SdlConnectionTest, once refactored, ran into failing tests because the order the tests are run in differed from AndroidTestCase to AndroidJUnit4. To resolve this issue I have annotated these two classes with `@FixMethodOrder(MethodSorters.JVM)` to ensure these tests are run in the right order.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: android/sdl_android/src/main/java/com/smartdevicelink/managers/video/VideoStreamManager.java [hunk 1]
```diff
@@ -146,6 +146,7 @@ public void onServiceError(SdlSession session, SessionType type, String reason)
 	private final OnRPCNotificationListener hmiListener = new OnRPCNotificationListener() {
 		@Override
 		public void onNotified(RPCNotification notification) {
+			Log.e(TAG, "TESTING");
```
Comment (bilal-alsharifi) [inline android/sdl_android/src/main/java/com/smartdevicelink/managers/video/VideoStreamManager.java:149]: can we remove this?

Comment (RHenigan) [reply android/sdl_android/src/main/java/com/smartdevicelink/managers/video/VideoStreamManager.java]: Yeah, thanks for catching that
