### PR TITLE
iOS alignment/lock screen

### LINKED ISSUE #1342: Change lock screen logo and ensure correct contrast
### Bug Report
The Java_Suite and iOS lock screen logos are currently different. The Java_Suite logo should change to align with the iOS logo (attached). Additionally, the iOS library does contrast checking against the background color of the lock screen to flip the logo color between white and black. The Java_Suite library should do the same thing.

logo

##### Reproduction Steps
1. [Step 1]
2. [Step 2]
3. [Step 3]

##### Expected Behavior
[Some expected behavior]

##### Observed Behavior
[Some observed behavior]

##### OS & Version Information
* Android Version: [What version of Android are you using when the bug occurred]
* SDL Android Version: [What version of the library has this bug been seen on]
* Testing Against: [What you tested with to observe this behavior]

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

### PR DESCRIPTION
**Pull request by JulianKast**
Fixes #1342 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android, Java SE, and Java EE

#### Core Tests
Enable Driver distraction when testing to get the lock screen to appear.

### Summary
Change the LockScreen icon to match iOS. Calculates color contrast to change icon color and text to white or black.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/SDLLockScreenActivity.java [hunk 1]
```diff
@@ -158,19 +168,85 @@ public void initializeActivity(Intent intent){
...
+	 *  Calculates the contrast of the background to determine if the Icon and Text color
+	 *  should be white or black
+	 * @return True if Background and Icon should be white, False if black
+	 */
+	private boolean shouldUseWhiteForegroundForBackgroundColor() {
+		float r = Color.red(backgroundColor) / 255f;
+		float b = Color.blue(backgroundColor) / 255f;
+		float g = Color.green(backgroundColor) / 255f;
+
+		// http://stackoverflow.com/a/3943023
```
Comment (RHenigan) [inline android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/SDLLockScreenActivity.java:221]: Do we typically reference stack overflow in the code like this?

File: android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/SDLLockScreenActivity.java [hunk 2]
```diff
@@ -64,6 +69,9 @@
 	private static final int MIN_SWIPE_DISTANCE = 200;
 	private boolean mIsDismissible;
 	private GestureDetector mGestureDetector;
+	private int backgroundColor = Color.parseColor("#394e60");
```
Comment (RHenigan) [inline android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/SDLLockScreenActivity.java:72]: Should "#394e60" be some sort of magic number? or maybe we can name backgroundColor something like defaultBackgroundColor

File: android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/SDLLockScreenActivity.java (hunk 1 above)
Comment (JulianKast) [reply android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/SDLLockScreenActivity.java:221]: This code was pulled from IOS and minor changes were made to convert to Java. Since IOS has it, I left it

File: android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/SDLLockScreenActivity.java (hunk 2 above)
Comment (JulianKast) [reply android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/SDLLockScreenActivity.java:72]: That is the default background color, I will change the name.

Comment (RHenigan) [reply android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/SDLLockScreenActivity.java:72]: Agreed, I was missing some of the context
