### PR TITLE
Attepted fix of NPE in #1783

### LINKED ISSUE #1783: NPE crash in BaseLifecycleManager on checkLifecycleConfiguration
### Bug Report
[Summary]
Crash in BaseSdlManager.checkLifecycleConfiguration on line 191. Attempting to call managerListener.managerShouldUpdateLifecycle() when smanagerListener value is null.

##### Reproduction Steps
Unfortunately unable to reproduce at the moment. This crash came from our Crashlytics logs and has only been observed from version 5.1 

##### OS & Version Information
* Android Version: Android 7 to 12
* SDL Android Version: from 5.1
* Testing Against: No tests as this came from Crashlytics logs.

##### Test Case, Sample Code, and / or Example App
None currently available. only crash Log
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'com.smartdevicelink.managers.lifecycle.LifecycleConfigurationUpdate com.smartdevicelink.managers.SdlManagerListener.managerShouldUpdateLifecycle(com.smartdevicelink.proxy.rpc.enums.Language, com.smartdevicelink.proxy.rpc.enums.Language)' on a null object reference
       at com.smartdevicelink.managers.BaseSdlManager.checkLifecycleConfiguration(BaseSdlManager.java:191)
       at com.smartdevicelink.managers.SdlManager$2.run(SdlManager.java:218)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:359)
       at android.app.ActivityThread.main(ActivityThread.java:7418)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

### PR DESCRIPTION
**Pull request by noah-livio**
Fixes #1783

This is not ready for review.

### Risk
None

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android, Java SE, and Java EE

#### Unit Tests
`testDisposeAfterRetryChangeRegistration()` - Creates a sample `SdlManager`, calls `retryChangeRegistration()` and then calls `dispose()`. This test will pass if no exceptions are thrown.

`testRetryChangeRegistrationAfterDispose()` - Creates a sample `SdlManager`, calls `dispose()` and then calls `retryChangeRegistration()`. This test will pass if no exceptions are thrown.

#### Core Tests
Both Core tests were performed in a modified version of Hello Sdl Android, while locally making `retryChangeRegistration()` public so it can be directly called in the app.

1. At the end of `SdlService.performWelcomeShow()` I called         `sdlManager.retryChangeRegistration()` then `sdlManager.dispose()`. As a result, the app did not crash and `SdlManager` did not throw a visible exception.

2. At the end of `SdlService.performWelcomeShow()` I called `sdlManager.dispose()` then `sdlManager.retryChangeRegistration()`. As a result, the app did not crash and `SdlManager` did not throw a visible exception.

Core version / branch / commit hash / module tested against: SDL Core v8.0.0 master 68f082169e0a40fccd9eb0db3c83911c28870f07
HMI name / version / branch / commit hash / module tested against: Generic HMI v0.11.0 master 47e0ad42f05b27adff61befd864e79c2ab4b8cec

### Summary
Converts local variable `handler` in `SdlManager.retryChangeRegistration()` to a private member of the class 
Creates private member `changeRegistrationRunnable` to replace anonymous `Runnable` in `SdlManager.retryChangeRegistration()`

Add `DebugTool` warning in the default constructor of `SdlManager` to let developers know not to use the constructor directly.

In `SdlManager.dismiss()`, remove `changeRegistrationRunnable` from `handler` if both are not null

In `BaseSdlManager.checkLifecycleConfiguration()` add a null check for `managerListener`

##### Breaking Changes
* None

##### Enhancements
* None

##### Bug Fixes
* Fixes #1783

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/SdlManagerTests.java [hunk 1]
```diff
@@ -422,4 +422,20 @@ public void onResponse(int correlationId, RPCResponse response) {
...
+        sdlManager.dispose();
+    }
+
+    @Test
+    public void testRetryChangeRegistrationAfterDispose() {
+        LockScreenConfig lockScreenConfig = new LockScreenConfig();
+        SdlManager sdlManager = createSampleManager("Test App", "test.test.test", lockScreenConfig);
+        sdlManager.dispose();
+        sdlManager.retryChangeRegistration();
+    }
```
Comment (RHenigan) [inline android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/SdlManagerTests.java:440]: I dont think these unit tests actually will catch what we are trying to prevent. If the `checkLifecycleConfiguration` method is updated to manually throw an exception these tests will still pass. It does not look like the code is waiting for the runnable to complete so I believe the tests are completing before the runnable even executes.

File: android/sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java [hunk 2]
```diff
@@ -91,6 +91,19 @@
...
+    private Runnable changeRegistrationRunnable = new Runnable() {
+        @Override
+        public void run() {
+            checkLifecycleConfiguration();
+            DebugTool.logInfo(TAG, "Retry Change Registration Count: " + changeRegistrationRetry);
+        }
+    };
+
+    public SdlManager(){
+        DebugTool.logWarning(TAG, "If this SdlManager was created without using SdlManager.Builder, most of its members are not initialized");
```
Comment (RHenigan) [inline android/sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java:104]:
```suggestion
        DebugTool.logWarning(TAG, "SdlManager must be created with SdlManager.Builder");
```

File: base/src/main/java/com/smartdevicelink/managers/BaseSdlManager.java [hunk 3]
```diff
@@ -188,52 +188,46 @@ protected void checkLifecycleConfiguration() {
...
-                            if (lcu.getTtsName() != null) {
-                                ttsChunks = lcu.getTtsName();
-                            }
-
-                            if (lcu.getVoiceRecognitionCommandNames() != null) {
-                                vrSynonyms = lcu.getVoiceRecognitionCommandNames();
-                            }
-                        } else {
-                            DebugTool.logError(TAG, "Change Registration onError: " + response.getResultCode() + " | Info: " + response.getInfo());
-                            retryChangeRegistration();
```
Comment (RHenigan) [inline base/src/main/java/com/smartdevicelink/managers/BaseSdlManager.java:232]: Looks like this code was missed, this should not be removed

File: android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/SdlManagerTests.java (hunk 1 above)
Comment (RHenigan) [inline android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/SdlManagerTests.java:440]: I dont think these unit tests actually will catch what we are trying to prevent. If the checkLifecycleConfiguration method is updated to manually throw an exception these tests will still pass. It does not look like the code is waiting for the runnable to complete so I believe the tests are completing before the runnable even executes.

File: android/sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java (hunk 2 above)
Comment (RHenigan) [inline android/sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java:104]:
```suggestion
        DebugTool.logWarning(TAG, "SdlManager must be created with SdlManager.Builder");
```

File: base/src/main/java/com/smartdevicelink/managers/BaseSdlManager.java (hunk 3 above)
Comment (noah-livio) [reply base/src/main/java/com/smartdevicelink/managers/BaseSdlManager.java:232]: Good catch

File: android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/SdlManagerTests.java (hunk 1 above)
Comment (noah-livio) [reply android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/SdlManagerTests.java:440]: Think I should just remove them then?

Comment (RHenigan) [reply android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/SdlManagerTests.java:440]: Yeah, I dont believe these tests are needed

Comment (noah-livio) [reply android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/SdlManagerTests.java:440]: Okay, will do

**Comment by noah-livio** [comment]
Fixes #1783

This is not ready for review.

### Risk
None

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [] I have run the unit tests with this PR - None
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android, Java SE, and Java EE

#### Unit Tests
- None

#### Core Tests
Both Core tests were performed in a modified version of Hello Sdl Android, while locally making `retryChangeRegistration()` public so it can be directly called in the app.

1. At the end of `SdlService.performWelcomeShow()` I called         `sdlManager.retryChangeRegistration()` then `sdlManager.dispose()`. As a result, the app did not crash and `SdlManager` did not throw a visible exception.

2. At the end of `SdlService.performWelcomeShow()` I called `sdlManager.dispose()` then `sdlManager.retryChangeRegistration()`. As a result, the app did not crash and `SdlManager` did not throw a visible exception.

Core version / branch / commit hash / module tested against: SDL Core v8.0.0 master 68f082169e0a40fccd9eb0db3c83911c28870f07
HMI name / version / branch / commit hash / module tested against: Generic HMI v0.11.0 master 47e0ad42f05b27adff61befd864e79c2ab4b8cec

### Summary
Converts local variable `handler` in `SdlManager.retryChangeRegistration()` to a private member of the class 
Creates private member `changeRegistrationRunnable` to replace anonymous `Runnable` in `SdlManager.retryChangeRegistration()`

Add `DebugTool` warning in the default constructor of `SdlManager` to let developers know not to use the constructor directly.

In `SdlManager.dismiss()`, remove `changeRegistrationRunnable` from `handler` if both are not null

In `BaseSdlManager.checkLifecycleConfiguration()` add a null check for `managerListener`

### Changelog
##### Breaking Changes
* None

##### Enhancements
* None

##### Bug Fixes
* Fixes #1783

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

**Review by RHenigan — APPROVED** [review]
