### PR TITLE
Bugfix/issue 1824 Add missing DisplayCapabilities info and window ID

### LINKED ISSUE #1824: `DisplayCapabilities`  `ScreenParams` null in SystemCapabilityManager
### Bug Summary

When accessing displayCapabilities via the systemCapabilityManager screenParams and mediaClockFormats are empty. In The RAIR, the screenParams are not nil and mediaClockFormats are not empty. windowID is also nil from defaultMainWindowCapability

screenParams should not be null in the systemCapabilityManager.
mediaClockFormats should not be empty in the systemCapabilityManager.
windowID should not be null in systemCapabilityManager.

### Reproduction Steps

1. Connect app to manticore
2. Get `DefaultMainWindowCapability` and `DisplayCapabilities` via the `SystemCapabilityManager`
3. Check ScreenParams, MediaClockFormat, and windowID.

```
        WindowCapability windowCapability = sdlManager.getSystemCapabilityManager().getDefaultMainWindowCapability();
        DisplayCapabilities displayCapabilities = (DisplayCapabilities) sdlManager.getSystemCapabilityManager().getCapability(SystemCapabilityType.DISPLAY, null, false);
    
        ScreenParams screenParams = displayCapabilities.getScreenParams();
        List<MediaClockFormat> mediaClockFormat = displayCapabilities.getMediaClockFormats();
        int windowID = windowCapability.getWindowID();
```

Expected Behavior:
ScreenParams should not be null, MediaClockFormats should not be empty and windowID should not be null.
Observed Behavior:
ScreenParams are null, MediaClockFormats are empty and windowID is null.

### Which projects have you seen this bug on?

_No response_

### Android Version(s)

n/a

### Android Device(s)

n/a

### sdl_java_suite Version

5.5.0

### Testing Environment(s)

```markdown
Manticore
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by JulianKast**
Fixes #1824 

This PR is **[ready]** for review.

### Risk
This PR makes **[no]** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android, Java SE, and Java EE

#### Unit Tests
Unit test were updated in SystemCapabilityManagerTests.java

#### Core Tests
Tested to verify that ScreenParams and MediaClockFormats from SystemCapabilityManager `DisplayCapabilities` matched `DisplayCapabilities` from RAIR.

Test retrieving DefaultMainWindowCapability from SystemCapabilityManager modifying it then retrieving it again from SystemCapabilityManager to verify that it was not modified in the manager. 

Core version / branch / commit hash / module tested against: Manticore v 2.10.0
HMI name / version / branch / commit hash / module tested against: Manticore v 2.10.0

### Summary
When we get the new `DisplayCapability`, we update the old deprecated `DisplayCapabilities` based on the new `DisplayCapability`. When we do that, `ScreenParams`  and MediaClockFormats which are a part of `DisplayCapabilities` don't get set properly.

This pr checks cached DisplayCapabilities for `ScreenParams`  and  `MediaClockFormats` and updates them to the updated capabilities being set in SystemCapabilityManager as well as updates`getWindowCapability` to clone and set the` windowID` property. 

##### Bug Fixes
* Fixes updating `DisplayCapabilities`

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseSystemCapabilityManager.java [hunk 1]
```diff
@@ -172,6 +172,11 @@ private DisplayCapabilities createDeprecatedDisplayCapabilities(String displayNa
         // if there are imageTypes in the response, we must assume graphics are supported
         convertedCapabilities.setGraphicSupported(defaultMainWindow.getImageTypeSupported() != null && defaultMainWindow.getImageTypeSupported().size() > 0);
 
+        if (cachedSystemCapabilities.containsKey(SystemCapabilityType.DISPLAY)) {
+            DisplayCapabilities displayCapabilitiesOld = (DisplayCapabilities) cachedSystemCapabilities.get(SystemCapabilityType.DISPLAY);
+            convertedCapabilities.setScreenParams(displayCapabilitiesOld.getScreenParams());
+
```
Comment (noah-livio) [inline base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseSystemCapabilityManager.java:178]:
```suggestion
```

**Review by noah-livio — CHANGES_REQUESTED** [review]
Admittedly, I still don't completely understand exactly why they work, but these changes do fix the targeted issue and don't seem to create any new ones. The code is clean and seems safely limited in scope.

Just requesting the removal of any empty line for formatting at this point.

**Review by noah-livio — APPROVED** [review]

**Review by jacobkeeler — APPROVED** [review]

File: base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseSystemCapabilityManager.java [hunk 2]
```diff
@@ -246,6 +255,7 @@ public WindowCapability getWindowCapability(int windowID) {
         for (WindowCapability windowCapability : display.getWindowCapabilities()) {
             int currentWindowID = windowCapability.getWindowID() != null ? windowCapability.getWindowID() : PredefinedWindows.DEFAULT_WINDOW.getValue();
             if (currentWindowID == windowID) {
+                windowCapability.setWindowID(windowID);
```
Comment (jacobkeeler) [inline base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseSystemCapabilityManager.java:258]: Any particular reason that we're editing this value in a getter? It seems to me that this would basically act identically without this modification, and it's not great practice to modify internal values within a getter.

Comment (jacobkeeler) [reply base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseSystemCapabilityManager.java:258]: I suppose if you need the caller to have this windowID in all cases, you could maybe make a copy of the capability object and modify that?

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

File: base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseSystemCapabilityManager.java (hunk 2 above)
Comment (JulianKast) [reply base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseSystemCapabilityManager.java:259]: I added a comment in the code, explaining, This is in alignment with iOS and JavaScript PR's for this issue that are linked in the comments on the trello card.

Comment (jacobkeeler) [reply base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseSystemCapabilityManager.java:259]: Sorry, I suppose I was just saying that `DEFAULT_WINDOW` was logically equivalent to `null` in this case, based on the spec. 

I'm aware that this was part of the alignment with iOS. Unfortunately it's still bad practice. Realistically if we want this value to always be present, we should be ensuring this when the value is set instead. 

That said, here's a potential alternative option which doesn't involve too many changes, and doesn't modify the capabilities directly:
```suggestion
                if (windowCapability.getWindowID() == null) {
                    WindowCapability updatedCaps = new WindowCapability(windowCapability.getStore());
                    updatedCaps.setWindowID(PredefinedWindows.DEFAULT_WINDOW.getValue());
                    return updatedCaps;
                }
```

Comment (JulianKast) [reply base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseSystemCapabilityManager.java]: Because developers can modify the stored window capability that they get through SystemCapabilityManager, I cloned them to prevent that.

File: base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseSystemCapabilityManager.java [hunk 3]
```diff
@@ -246,7 +255,11 @@ public WindowCapability getWindowCapability(int windowID) {
         for (WindowCapability windowCapability : display.getWindowCapabilities()) {
             int currentWindowID = windowCapability.getWindowID() != null ? windowCapability.getWindowID() : PredefinedWindows.DEFAULT_WINDOW.getValue();
             if (currentWindowID == windowID) {
-                return windowCapability;
+                // Clone WindowCapability to prevent modification of stored WindowCapability in SystemCapabilityManager
+                WindowCapability updatedCaps = (WindowCapability) windowCapability.clone();
+                // A null windowID is assumed to be the DefaultWindow according to the spec, but that can be hard for developers to check, so set it explicitly.
+                updatedCaps.setWindowID(windowID);
+                return updatedCaps;
```
Comment (jacobkeeler) [inline base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseSystemCapabilityManager.java:262]:
```suggestion
                WindowCapability windowCapabilityCopy = (WindowCapability) windowCapability.clone();
                // A null windowID is assumed to be the DefaultWindow according to the spec, but that can be hard for developers to check, so set it explicitly.
                windowCapabilityCopy.setWindowID(windowID);
                return windowCapabilityCopy;
```
Original variable name was really just a placeholder, so perhaps this would be better this time around? (hard to come up with a good name for this one)

**Review by jacobkeeler — APPROVED** [review]
