### PR TITLE
Bugfix/issue 1835 AlertManager File upload fix

### LINKED ISSUE #1835: Images not displaying correctly on Alerts sent via AlertManager
### Bug Summary

Images are not displaying correctly on Alerts sent via AlertManager. That is because in `PresentAlertOperation.alertRpc` we check hasUploadedFile instead of fileNeedsUploaded

```
        if (alertView.getIcon() != null && supportsAlertIcon() && !(fileManager.get().hasUploadedFile(alertView.getIcon()))) {
            alert.setAlertIcon(alertView.getIcon().getImageRPC());
        }
```
When it should be: (remove ! when checking fileManager that it has been uploaded)

```
        if (alertView.getIcon() != null && supportsAlertIcon() && !fileManager.get().fileNeedsUpload(alertView.getIcon())) {
            alert.setAlertIcon(alertView.getIcon().getImageRPC());
        }
```

### Reproduction Steps

1. Create AlertView with SdlArtwork
2. Send AlertView via sdlManger to present alert

Expected Behavior:
Alert should display with the correct image

Observed Behavior:
Alert displayed with place holder image.

### Which projects have you seen this bug on?

_No response_

### Android Version(s)

n/a

### Android Device(s)

_No response_

### sdl_java_suite Version

5.5.0

### Testing Environment(s)

```markdown
Manticore
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by JulianKast**
Fixes #1835 

This PR is **[ready]** for review.

### Risk
This PR makes **[no]** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android, Java SE, and Java EE

#### Unit Tests
Unit test were updated in PresentAlertOperationTest.

#### Core Tests
Test sending Alert with Image via ScreenManager and verify that the image correctly appears.

Core version / branch / commit hash / module tested against: Manticore
HMI name / version / branch / commit hash / module tested against: Manticore

### Summary
Changed check fileManager.hasUploadedFile to fileManager.fileNeedsUpload.

##### Bug Fixes
* Fixes incorrect conditional statement when creating AlertRPC so Images will appear correctly

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: base/src/main/java/com/smartdevicelink/managers/screen/PresentAlertOperation.java [hunk 1]
```diff
@@ -57,6 +57,7 @@
 
 import java.lang.ref.WeakReference;
 import java.util.ArrayList;
+import java.util.HashSet;
```
Comment (ChloeMJM) [inline base/src/main/java/com/smartdevicelink/managers/screen/PresentAlertOperation.java:60]: Remove unused import.

**Review by ChloeMJM — CHANGES_REQUESTED** [review]
Remove unused imports.

**Review by ChloeMJM — APPROVED** [review]
