### PR TITLE
1738 - Soft button manager image upload fix 

### LINKED ISSUE #1738: ScreenManager tries to upload images even if they are not supported
### Bug Report
It seems the `ScreenManager` tries to upload images on Sync 2 even if the dynamic images are not supported. That doesn't crash the app but it just sends RPCs when there is no need for that. It also logs some error messages like the following:

```
E/FileManager: 5.2.0: File named icon.png failed to upload. Max number of upload attempts reached.
E/FileManager: 5.2.0: File named image1.png failed to upload. Max number of upload attempts reached.
E/SoftButtonReplaceOperation: 5.2.0: Error uploading soft button artworks: [image1.png]
E/FileManager: 5.2.0: File named image2.png failed to upload. Max number of upload attempts reached.
E/SoftButtonReplaceOperation: 5.2.0: Error uploading soft button artworks: [image2.png]
```

The potential reason for the issue is that Sync 2 sends `RegisterAppInterfaceRespomse` with the following values :
```
RegisterAppInterfaceRespomse.displayCapabilities.graphicSupported = false
RegisterAppInterfaceRespomse.softButtonCapabilities.imageSupported = true
```
The `SoftButttonManager` (and possibly other managers) depends on `ImageSupported` and thinks the images are supported when in reality they are not.

##### Reproduction Steps
1. Run SDL app on Sync 2 TDK
2. Use the SoftButtonManager to set buttons with images

##### Expected Behavior
Images for the buttons shouldn't be uploaded because the TDK doesn't support dynamic images.

##### Observed Behavior
`SoftButtonmanager` tries to upload the images then fail

##### OS & Version Information
* Android Version: 11
* SDL Android Version: 5.2
* Testing Against: Sync 2

### PR DESCRIPTION
**Pull request by JulianKast**
Fixes #1738 

This PR is **[ready]** for review.

### Risk
This PR makes **[minor]** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android, Java SE, and Java EE

#### Unit Tests
Unit tests were updated with the new parameter and one test was added in SoftButtonManagerTest

#### Core Tests
Tested sending a softbutton with an image, verifying that the image displays.

```
        SoftButtonState softButtonState = new SoftButtonState("artworkTest", "Button", new SdlArtwork("testArtwork1", FileType.GRAPHIC_PNG, R.drawable.ic_sdl, true));

        SoftButtonObject softButtonObject = new SoftButtonObject("jk", softButtonState, new SoftButtonObject.OnEventListener() {
            @Override
            public void onPress(SoftButtonObject softButtonObject, OnButtonPress onButtonPress) {
            }

            @Override
            public void onEvent(SoftButtonObject softButtonObject, OnButtonEvent onButtonEvent) {

            }
        });
        sdlManager.getScreenManager().setSoftButtonObjects(Collections.singletonList(softButtonObject));
```

Core version / branch / commit hash / module tested against: Core 8.1, Manticore and Sync 3
HMI name / version / branch / commit hash / module tested against: Generic_HMI

### Summary
This PR works around a bug when connecting to Sync 2.0 head units that causes the app to attempt to upload a dynamic soft button images that will never work. This wastes bandwidth and time.

The issue happens because Sync 2.0 doesn't support softButtonCapabilities, so the library assumes all capabilities are available. However, Sync 2.0 does report that all graphics are unsupported in RAIR.displayCapabilities.graphicSupported.

Static images are supported by Sync 2.0 and should still upload on softbuttons.

##### Bug Fixes
* Fixes attempted uploads of image data on SDL 2.0

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: base/src/main/java/com/smartdevicelink/managers/screen/BaseSoftButtonManager.java [hunk 1]
```diff
@@ -71,8 +71,10 @@ abstract class BaseSoftButtonManager extends BaseSubManager {
     private static final String TAG = "BaseSoftButtonManager";
     private final WeakReference<FileManager> fileManager;
     SoftButtonCapabilities softButtonCapabilities;
+    boolean isGraphicSupported;
     private CopyOnWriteArrayList<SoftButtonObject> softButtonObjects;
     private HMILevel currentHMILevel;
+    private DisplayCapabilities displayCapabilities;
```
Comment (joeljfischer) [inline base/src/main/java/com/smartdevicelink/managers/screen/BaseSoftButtonManager.java:77]: I don't think you need to store this, just `isGraphicSupported`, right?

File: android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/SoftButtonManagerTests.java [hunk 2]
```diff
@@ -140,6 +140,7 @@ public Void answer(InvocationOnMock invocation) {
         taskmaster.start();
         when(internalInterface.getTaskmaster()).thenReturn(taskmaster);
         softButtonManager = new SoftButtonManager(internalInterface, fileManager);
+        softButtonManager.isGraphicSupported = true;
```
Comment (joeljfischer) [inline android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/SoftButtonManagerTests.java:143]: You probably should have a test where this is NO and images are not sent

**Review by joeljfischer — CHANGES_REQUESTED** [review]
A few small items

File: base/src/main/java/com/smartdevicelink/managers/screen/SoftButtonReplaceOperation.java [hunk 3]
```diff
@@ -30,14 +31,16 @@ class SoftButtonReplaceOperation extends Task {
...
 
-    SoftButtonReplaceOperation(ISdl internalInterface, FileManager fileManager, SoftButtonCapabilities softButtonCapabilities, CopyOnWriteArrayList<SoftButtonObject> softButtonObjects, String currentMainField1) {
+    SoftButtonReplaceOperation(ISdl internalInterface, FileManager fileManager, SoftButtonCapabilities softButtonCapabilities, CopyOnWriteArrayList<SoftButtonObject> softButtonObjects, String currentMainField1, Boolean isGraphicSupported) {
         super("SoftButtonReplaceOperation");
         this.internalInterface = new WeakReference<>(internalInterface);
         this.fileManager = new WeakReference<>(fileManager);
         this.softButtonCapabilities = softButtonCapabilities;
         this.softButtonObjects = softButtonObjects;
         this.currentMainField1 = currentMainField1;
+        this.isGraphicSupported = isGraphicSupported;
```
Comment (joeygrover) [inline base/src/main/java/com/smartdevicelink/managers/screen/SoftButtonReplaceOperation.java:43]: Can we refactor this to be `isDynamicGraphicSupported`? I just think in the future it will be much clearer what this actually means.

**Review by joeygrover — CHANGES_REQUESTED** [review]

**Review by joeygrover — APPROVED** [review]
