### PR TITLE
Refactor ChoiceSetManager to Fix several bugs

### LINKED ISSUE #1717: Back-to-back choice sets can fail
### Bug Report
There is a bug in the `BaseChoiceSetManager` where back-to-back choice sets can fail. Because the `PresentChoiceSetOperation` uses the standard `CompletionListener`,  which runs adter the operation completes and the noext one starts, if two present operations are next to each other, the second should run, but there are cases where that does not happen. this is because the `CompletionListener` clears the `pendingPresentationSet`, which may no longer be the running presentation set.

Instead, we should do as we do in the alert manager and add prending presentation to the queue and cancel previous non-executing ones if a new one is added.

##### Reproduction Steps
1. Create a choice set
2. Before an option is pressed, present a new choice set

##### Expected Behavior
The second choice set appears

##### Observed Behavior
The second choice set fails to appear because the choice set is `null` in the `PresentChoiceSetOperation`.

### PR DESCRIPTION
**Pull request by RHenigan**
Fixes #1717, #1718

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android, Java SE, and Java EE

#### Unit Tests
Updated unit test for new operation

#### Core Tests
Tested send in a presentation, then sending another presentation when the first has a button pressed
Smoke Tests for choiceset manager

Core version / branch / commit hash / module tested against: Manticore (SDL v7.1.1)
HMI name / version / branch / commit hash / module tested against: (Generic HMI v0.10.0)

### Summary
1. This PR rewrites the preload / present operations into one operation to solve some queueing problems. The operation will now figure out what it has to do based on how it is initialized.
2. This PR changes cancelation behavior. Before if you sent a present, then another present, the manager would try to cancel previous ones. Now they will be queued and the dev can cancel previous ones if desired.
3. This PR fixes strange deletion behavior. Before if a delete came in while a preload / present was happening, the manager would try to delete choices from the upload. Now it will wait until the delete operation comes around and delete at that time. This allows proper behavior around preload -> present -> delete situations.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadChoicesCompletionListener.java [hunk 1]
```diff
@@ -0,0 +1,13 @@
+package com.smartdevicelink.managers.screen.choiceset;
+
+import java.util.HashSet;
+
+public interface PreloadChoicesCompletionListener {
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadChoicesCompletionListener.java:5]: Can you make this internal to BaseChoiceSetManager like what you did on this PR: https://github.com/smartdevicelink/sdl_java_suite/pull/1716/files, also just create one interface to use, as this does the same thing as the `DeleteChoicesCompletingListener` so something like: 

```
    interface ChoiceCompletionListener {
        void onComplete(boolean success, HashSet<ChoiceCell> failedChoiceCells);
    }
```

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 2]
```diff
@@ -0,0 +1,787 @@
...
+        } else {
+            ArrayList<ChoiceCell> strippedCellsCopy = (ArrayList<ChoiceCell>) removeUnusedProperties(cellsToUpload);
+            addUniqueNamesBasedOnStrippedCells(strippedCellsCopy, cellsToUpload);
+        }
+        cellsToUpload.removeAll(loadedCells);
+    }
+
+    List<ChoiceCell> removeUnusedProperties(List<ChoiceCell> choiceCells) {
+        List<ChoiceCell> strippedCellsClone = cloneChoiceCellList(choiceCells);
+        //Clone Cells
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java:485]: This is my fault from a previous PR as this is just copied from BaseChoiceSetManager.
```suggestion
        // Clone Cells
```

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 3]
```diff
@@ -0,0 +1,787 @@
...
+        pi.setHelpPrompt(choiceSet.getHelpPrompt());
+        pi.setTimeoutPrompt(choiceSet.getTimeoutPrompt());
+        pi.setVrHelp(choiceSet.getVrHelpList());
+        pi.setTimeout(choiceSet.getTimeout() * 1000);
+        pi.setInteractionLayout(getLayoutMode());
+        pi.setCancelID(cancelID);
+        return pi;
+    }
+
+    //Choice Uniqueness
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java:472]:
```suggestion
    // Choice Uniqueness
```

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 4]
```diff
@@ -0,0 +1,787 @@
...
+
+            counter = dictCounter.get(cell);
+
+            if (counter > 1) {
+                unstrippedCells.get(i).setUniqueText(unstrippedCells.get(i).getText() + " (" + counter + ")");
+            }
+        }
+    }
+
+    //Finding Cells
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java:570]:
```suggestion
    // Finding Cells
```

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 5]
```diff
@@ -0,0 +1,787 @@
...
+    private ChoiceCell cellFromChoiceId(int choiceId) {
+        for (ChoiceCell cell : this.cellsToUpload) {
+            if (cell.getChoiceId() == choiceId) {
+                return cell;
+            }
+        }
+        return null;
+    }
+
+    //Assembling Choice RPCs
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java:580]:
```suggestion
    // Assembling Choice RPCs
```

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 6]
```diff
@@ -0,0 +1,787 @@
...
+
+    boolean shouldSendChoicePrimaryImage() {
+        return templateSupportsImageField(ImageFieldName.choiceImage);
+    }
+
+    boolean shouldSendChoiceSecondaryImage() {
+        return templateSupportsImageField(ImageFieldName.choiceSecondaryImage);
+    }
+
+    //SDL Notifications
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java:644]:
```suggestion
    // SDL Notifications
```

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 7]
```diff
@@ -0,0 +1,787 @@
...
+            } else {
+                DebugTool.logError(TAG, "Internal interface null - could not send cancel interaction for choice set");
+            }
+        } else {
+            DebugTool.logInfo(TAG, "Canceling a choice set that has not yet been sent to Core");
+            this.cancelTask();
+        }
+    }
+
+    //Present Helpers
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java:443]:
```suggestion
    // Present Helpers
```

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 8]
```diff
@@ -0,0 +1,787 @@
...
+                                });
+                            }
+                        });
+                    }
+                });
+            }
+        });
+    }
+
+    //PRELOAD OPERATION METHODS
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java:198]:
```suggestion
    // Preload Operation Methods
```

**Review by JulianKast — CHANGES_REQUESTED** [review]
@RHenigan after my first review, I noticed a few small things.

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 9]
```diff
@@ -0,0 +1,787 @@
...
+
+    boolean templateSupportsImageField(ImageFieldName name) {
+        return defaultMainWindowCapability == null || ManagerUtility.WindowCapabilityUtility.hasImageFieldOfName(defaultMainWindowCapability, name);
+    }
+
+    public void setLoadedCells(HashSet<ChoiceCell> loadedCells) {
+        this.loadedCells = loadedCells;
+    }
+
+    public HashSet<ChoiceCell> getLoadedCells() {
```
[the remark this answers is not in the document]
Comment (RHenigan) [reply base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java]: Currently it was not being used and neither was the getter method in DeleteChoicesOperation, I have removed them for now

**Review by JulianKast — CHANGES_REQUESTED** [review]

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 10]
```diff
@@ -0,0 +1,820 @@
...
+                    choiceError = false;
+                }
+
+                @Override
+                public void onResponse(int correlationId, RPCResponse response) {
+                    if (!response.getSuccess()) {
+                        DebugTool.logError(TAG, "There was an error uploading a choice cell: " + response.getInfo() + " resultCode: " + response.getResultCode());
+                        choiceError = true;
+                    } else {
+                        loadedCells.add(cellFromChoiceId(correlationId));
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java:299]: correlationID does not translate to choiceCell ID so loadedCells are always empty, prompting cells to be uploaded everytime you go to present

**Review by JulianKast — CHANGES_REQUESTED** [review]

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/DeleteChoicesOperation.java [hunk 11]
```diff
@@ -93,23 +103,57 @@ public void onFinished() {
...
                             if (completionListener != null) {
-                                completionListener.onComplete(false);
+                                completionListener.onComplete(false, loadedCells);
                             }
                             DebugTool.logError(TAG, "Failed to delete choice: " + response.getInfo() + " | Corr ID: " + correlationId);
 
                             DeleteChoicesOperation.super.onFinished();
+                        } else {
+                            if (loadedCells != null) {
+                                loadedCells.remove(loadedCellFromChoiceId(correlationId));
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/DeleteChoicesOperation.java:113]: I found an issue, Steps to show error:
Step 1: Upload a `ChoiceSet`.
Step 2: Present `ChoiceSet` and select an item.
Step 3: In your `ChoiceSetSelectionListener` retrieve the list of uploaded `ChoiceCell`s and delete one of them.
Step 4: Present `ChoiceSet`

Observed: 
Errors: 

```
2021-09-13 15:58:07.635 28442-28442/com.sdl.hellosdlandroid E/PreloadPresentChoicesOperation: 5.2.0: Presenting Choice set failed: null
2021-09-13 15:58:07.635 28442-28442/com.sdl.hellosdlandroid E/BaseChoiceSetManager: 5.2.0: Present finished but an unhandled state occurred and callback failed
```

Expected: 
The deleted ChoiceCell should be uploaded again and the ChoiceSet should be present.

I traced it back to here, the Correlation ID was 53 and the ChoiceCell ID was 3.

Code I used for testing:
Add this code to `onChoiceSelected` in hello_sdl

```
 HashSet<ChoiceCell> choiceCellHashSet = sdlManager.getScreenManager().getPreloadedChoices();
 List<ChoiceCell> choiceCellList = new ArrayList<>(choiceCellHashSet);
 sdlManager.getScreenManager().deleteChoices(Collections.singletonList(choiceCellList.get(1)));
```

**Review by JulianKast — CHANGES_REQUESTED** [review]

**Review by JulianKast — CHANGES_REQUESTED** [review]

File: android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/choiceset/ChoiceSetManagerTests.java [hunk 12]
```diff
@@ -38,6 +38,7 @@
 
 import com.livio.taskmaster.Taskmaster;
 import com.smartdevicelink.managers.BaseSubManager;
+import com.smartdevicelink.managers.CompletionListener;
```
Comment (JulianKast) [inline android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/choiceset/ChoiceSetManagerTests.java:41]: There are some unused imports in this class related to removed code

File: android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperationTests.java [hunk 13]
```diff
@@ -0,0 +1,444 @@
...
+import org.junit.Test;
+import org.junit.runner.RunWith;
+import org.mockito.invocation.InvocationOnMock;
+import org.mockito.stubbing.Answer;
+
+import java.util.Arrays;
+import java.util.Collections;
+import java.util.HashSet;
+import java.util.LinkedHashSet;
+import java.util.List;
```
Comment (JulianKast) [inline android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperationTests.java:44]:
```suggestion
```

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/BaseChoiceSetManager.java [hunk 14]
```diff
@@ -94,18 +94,14 @@
     WindowCapability defaultMainWindowCapability;
     String displayName;
     SystemContext currentSystemContext;
-    HashSet<ChoiceCell> preloadedChoices, pendingPreloadChoices;
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/BaseChoiceSetManager.java:97]: There are some unused imports in this class related to removed code

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 15]
```diff
@@ -0,0 +1,924 @@
...
+ */
+
+package com.smartdevicelink.managers.screen.choiceset;
+
+import androidx.annotation.NonNull;
+
+import com.livio.taskmaster.Task;
+import com.smartdevicelink.managers.CompletionListener;
+import com.smartdevicelink.managers.ISdl;
+import com.smartdevicelink.managers.ManagerUtility;
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java:43]:
```suggestion
```

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 16]
```diff
@@ -0,0 +1,924 @@
...
+    private final WindowCapability defaultMainWindowCapability;
+    private final String displayName;
+    private final ArrayList<ChoiceCell> cellsToUpload;
+    private final BaseChoiceSetManager.ChoicesOperationCompletionListener completionListener;
+    private final ChoiceSetSelectionListener selectionListener;
+    private final boolean isVROptional;
+    private boolean choiceError = false;
+    private HashSet<ChoiceCell> loadedCells;
+    private final ChoiceSet choiceSet;
+    //Start choiceId at 1 to ensure all HMIs handle it https://github.com/smartdevicelink/generic_hmi/commit/b292fbbec095b9ce11b520d47ec95b6fcff8e247
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java:99]:
```suggestion
    // Start choiceId at 1 to ensure all HMIs handle it https://github.com/smartdevicelink/generic_hmi/commit/b292fbbec095b9ce11b520d47ec95b6fcff8e247
```

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 17]
```diff
@@ -0,0 +1,924 @@
...
+
+    private void assignIdsToCells(ArrayList<ChoiceCell> cells) {
+        ArrayList<Integer> usedIds = new ArrayList<>();
+        for (ChoiceCell cell : loadedCells) {
+            usedIds.add(cell.getChoiceId());
+        }
+        Collections.sort(usedIds);
+        ArrayList<Integer> sortedUsedIds = (ArrayList<Integer>) usedIds.clone();
+
+        //Loop through the cells we need ids for. Get and assign those ids
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java:550]:
```suggestion
        // Loop through the cells we need ids for. Get and assign those ids
```

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 18]
```diff
@@ -0,0 +1,924 @@
...
+        for (int i = 0; i < cells.size(); i++) {
+            int cellId = nextChoiceIdBasedOnUsedIds(sortedUsedIds);
+            cells.get(i).setChoiceId(cellId);
+
+            //Insert the ids into the usedIds sorted array in the correct position
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java:555]:
```suggestion
            // Insert the ids into the usedIds sorted array in the correct position
```

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 19]
```diff
@@ -0,0 +1,924 @@
...
+                    break;
+                } else if (j == (sortedUsedIds.size() - 1)) {
+                    sortedUsedIds.add(cellId);
+                    break;
+                }
+            }
+        }
+    }
+
+    //Find the next available choice is. Takes into account the loaded cells to ensure there are not duplicates
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java:568]:
```suggestion
    // Find the next available choice is. Takes into account the loaded cells to ensure there are not duplicates
```

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 20]
```diff
@@ -0,0 +1,924 @@
...
+    // @param usedIds The already loaded cell ids
+    // @return The choice id between 0 - 65535, or Not Found if no cell ids were available
+    private int nextChoiceIdBasedOnUsedIds(ArrayList<Integer> usedIds) {
+        //Check if we are entirely full, or if we've advanced beyond the max value, loop back
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java:572]:
```suggestion
        // Check if we are entirely full, or if we've advanced beyond the max value, loop back
```

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 21]
```diff
@@ -0,0 +1,924 @@
...
+        if (reachedMaxIds) {
+            // We've looped all the way around, so we need to check loaded cells
+            // Sort the set of cells by the choice id so that we can more easily check which slots are available
+            if (usedIds.size() >= (MAX_CHOICE_ID + 1)) {
+                //If we've maxed out our slots, return the max value
+                choiceId = MAX_CHOICE_ID;
+                return choiceId;
+            }
+
+            //If the last value isn't the max value, just keep grabbing towards the max value
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java:587]:
```suggestion
            // If the last value isn't the max value, just keep grabbing towards the max value
```

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 22]
```diff
@@ -0,0 +1,924 @@
...
+            int lastUsedId = usedIds.get(usedIds.size() - 1);
+            if (lastUsedId < MAX_CHOICE_ID) {
+                choiceId = lastUsedId + 1;
+                return  choiceId;
+            }
+
+            //All our easy options are gone. Find and grab an empty slot from within the sorted list
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java:594]:
```suggestion
            // All our easy options are gone. Find and grab an empty slot from within the sorted list
```

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 23]
```diff
@@ -0,0 +1,924 @@
...
+            for (int i = 0; i < usedIds.size(); i++) {
+                int loopId = usedIds.get(i);
+                if (i != loopId) {
+                    //This slot is open because the cell id does not match an open sorted slot
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java:598]:
```suggestion
                    // This slot is open because the cell id does not match an open sorted slot
```

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 24]
```diff
@@ -0,0 +1,924 @@
...
+                    choiceId = i;
+                    return choiceId;
+                }
+            }
+
+            //This *shouldn't* be possible
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java:604]:
```suggestion
            // This *shouldn't* be possible
```

File: base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java [hunk 25]
```diff
@@ -0,0 +1,924 @@
...
+            choiceId = MAX_CHOICE_ID;
+            return choiceId;
+        } else {
+            //We haven't looped all the way around yet, so we'll just take the current number, then advance the item
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java:608]:
```suggestion
            // We haven't looped all the way around yet, so we'll just take the current number, then advance the item
```

**Review by JulianKast — CHANGES_REQUESTED** [review]
minor updates needed

**Review by JulianKast — APPROVED** [review]
