### PR TITLE
Bugfix/issue 1284 UploadFiles() doesn't handle static icons correctly

### LINKED ISSUE #1284: BaseFileManager UploadFiles handles static icons differently then UploadFile
### Bug Report
Currently, if the FileManage().UploadFile() is called on a static icon, it will know that the file is a static icon and not upload it. However, uploadFiles() doesn't have a check and will upload the file

##### Reproduction Steps
1. Upload a static icon with uploadFiles and check to see if it upload.

##### Expected Behavior
File does not upload

##### Observed Behavior
File uploads

### PR DESCRIPTION
**Pull request by JulianKast**
Fixes #1284 

This PR is **ready**

### Risk
This PR makes **no** API changes.

### Testing Plan
- [X] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [X] I have run the unit tests with this PR
- [X] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [X] I have tested Android, Java SE, and Java EE

#### Unit Tests
Added unit test to test to make sure static icons are not uploaded.

#### Core Tests
Tested using Manticore

### Summary
Added logic to align uploadFiles() to uploadFile() in baseFileManager to handle static Icons the same. Before uploadFiles would upload static icons and uploadFile would not and return the lister as success. Now uploadFiles will not upload static icons.

##### Bug Fixes
* Aligned uploadFiles with uploadFile in BaseFileManager to handle static Icons the same.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: base/src/main/java/com/smartdevicelink/managers/file/BaseFileManager.java [hunk 1]
```diff
@@ -383,19 +383,27 @@ private boolean shouldReUploadFile(String fileName, FileType fileType) {
 
 	/**
 	 * Attempts to upload a list of SdlFiles to core
-	 * @param files list of SdlFiles with file name and one of A) fileData, B) Uri, or C) resourceID set
+	 * @param files    list of SdlFiles with file name and one of A) fileData, B) Uri, or C) resourceID set
```
Comment (bilal-alsharifi) [inline base/src/main/java/com/smartdevicelink/managers/file/BaseFileManager.java]:
```suggestion
	 * @param files list of SdlFiles with file name and one of A) fileData, B) Uri, or C) resourceID set
```
There are some extra spaces here

Comment (JulianKast) [reply base/src/main/java/com/smartdevicelink/managers/file/BaseFileManager.java]: It was the code reformat, Fixed it.
