### PR TITLE
Android 14 add package to PendingIntents in RouterService

### LINKED ISSUE #1861: Android 14 Pending Intent must have a package
### Description

In Android 14 we are now required to add a package to pending intents.

 ["If an app creates a mutable pending intent with an intent that doesn't specify a component or package, the system now throws an exception."](https://developer.android.com/about/versions/14/behavior-changes-14#safer-intentsurl)

### PR DESCRIPTION
**Pull request by JulianKast**
Fixes #1861 

This PR is **[ready]** for review.

### Risk
This PR makes **[minor]** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android

#### Unit Tests
n/a

#### Core Tests
Note: Before you install a second and thrid app, unplug the phone from the computer and switch the build variant before deploying app to the phone otherwise Android Studio will kill the app. 
Or you can open each app up on the phone after deploying all three apps.

Test 1
Install 3 apps to the phone
Connect via Bluetooth to TDK
Observe all apps connect.

Test 2
Repeat test 1 but with release build versions of the apps.

Core version / branch / commit hash / module tested against: Sync 3
HMI name / version / branch / commit hash / module tested against: Sync 3

### Summary
This PR adds a package to pending intents in the RouterService to prevent an exception from being thrown in the RouterService.

##### Bug Fixes
* Add Package to pending intent to prevent an exception from being thrown due to API 34 restrictions. 

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java [hunk 1]
```diff
@@ -1858,6 +1860,7 @@ public void onTransportConnected(final TransportRecord record) {
             //the developer can use this pendingIntent to start their SdlService from the context of
             //the active RouterService
             Intent pending = new Intent();
+            pending.setPackage(SDL_PACKAGE);
```
Comment (joeygrover) [inline android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java:1863]: I think it is better to use the actual package of the currently running service than one that is generic one.

```suggestion
            pending.setPackage(getPackageName());
```

File: android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java [hunk 2]
```diff
@@ -2981,6 +2984,7 @@ private Intent createPingIntent() {
...
```
Comment (joeygrover) [inline android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java:2987]: See previous comment.

```suggestion
            pending.setPackage(getPackageName());
```

File: android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java [hunk 3]
```diff
@@ -159,6 +159,8 @@ public class SdlRouterService extends Service {
 
     public static final String REGISTER_WITH_ROUTER_ACTION = "com.sdl.android.register";
 
+    public static final String SDL_PACKAGE = "com.smartdevicelink";
+
```
Comment (joeygrover) [inline android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java:163]: See previous comment. 

```suggestion
```

**Review by joeygrover — CHANGES_REQUESTED** [review]

**Review by joeygrover — APPROVED** [review]
