### PR TITLE
Feature/android 12 fixes

### LINKED ISSUE #1732: Bluetooth Permission Requirements will change in Android 12
### Bug Report
Starting with android 12 new Bluetooth Runtime permissions are required. The `MultiplexBluetoothTransport` class will require the new `BLUETOOTH_SCAN` and `BLUETOOTH_CONNECT` Permissions

https://developer.android.com/about/versions/12/features/bluetooth-permissions

##### OS & Version Information
* Android Version: SDK 31

### PR DESCRIPTION
**Pull request by RHenigan**
Fixes #1732, #1751 and #1794 

This PR is **ready** for review.

### Risk
This PR makes **major** API changes.

### Testing Plan
- [X] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [X] I have run the unit tests with this PR
- [X] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [X] I have tested Android, Java SE, and Java EE

#### Unit Tests
N/A

#### Core Tests
Extensive smoke testing was done that is reflected in the Release Testing Template.
Targeting Android 11 should result in the same behavior as before
Target Android 12 tests include:
Connecting to SYNC over USB with BT permissions denied

> Router Service Should Start as expected and a notification should be presented to grant permissions

Connecting to SYNC over BT with BT permissions denied

> The Router Service should not be started

Connecting to SYNC over USB with BT permissions granted

> Router Service Should Start as expected and a notification should NOT be presented to grant permissions

Connecting to SYNC over BT with BT permissions granted 

> Router Service Should Start as expected

Connecting to SYNC over USB with BT permissions denied, granting permissions once connected, then connecting BT.

> Once BT connects, Router service should be connected over BT and USB

Connecting to SYNC with multiple apps targeting android 12 (one app with BT permissions granted, one with BT permissions denied).

> Router Service should be started for app with permissions, verify the app without permissions still connects to the router service.

Core version / branch / commit hash / module tested against: SYNC3
HMI name / version / branch / commit hash / module tested against: SYNC3

### Summary
This PR addresses the issues that have been introduced by targeting Android 12 as outlined in this proposal ([0345](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0345-android-12-issues.md)).

This includes:
* [Start SdlService from pendingIntent](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0345-android-12-issues.md)
* [Bluetooth Runtime Permissions](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0345-android-12-issues.md#bluetooth-runtime-permissions)
* [AndroidManifest Exported Flag](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0345-android-12-issues.md#androidmanifest-exported-flag)

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: android/hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/MainActivity.java [hunk 1]
```diff
@@ -1,27 +1,68 @@
...
-        } else if (BuildConfig.TRANSPORT.equals("TCP")) {
+            if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
+                if (!checkPermission()) {
+                    requestPermission();
+                }
+            } else if (BuildConfig.TRANSPORT.equals("TCP")){
+                //If we are connected to a module we want to start our SdlService
+                SdlReceiver.queryForConnectedService(this);
+            }
+        } else {
```
Comment (joeygrover) [inline android/hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/MainActivity.java:36]:
```suggestion
            if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.S
                    && !checkPermission()) {
                requestPermission();
                return;
            }
            //If we are connected to a module we want to start our SdlService
            SdlReceiver.queryForConnectedService(this);

        } else if (BuildConfig.TRANSPORT.equals("TCP")) {
```

Comment (joeygrover) [reply android/hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/MainActivity.java:36]: This logic needed to be cleaned up. Basically check for OS version and if permission is granted, if not request them. If OS is less than 12 or permissions are granted, query for the RS. The previous else if was in the wrong position for TCP.

File: android/sdl_android/src/main/java/com/smartdevicelink/transport/USBAccessoryAttachmentActivity.java [hunk 2]
```diff
@@ -167,6 +167,7 @@ public void onComplete(Vector<ComponentName> routerServices) {
                         return;
                     }
                     serviceIntent.setAction(TransportConstants.BIND_REQUEST_TYPE_ALT_TRANSPORT);
+                    serviceIntent.putExtra(TransportConstants.CONNECTION_TYPE_EXTRA, TransportConstants.ACTION_USB_ACCESSORY_ATTACHED);
```
Comment (joeygrover) [inline android/sdl_android/src/main/java/com/smartdevicelink/transport/USBAccessoryAttachmentActivity.java:170]:
```suggestion
                    serviceIntent.putExtra(TransportConstants.CONNECTION_TYPE_EXTRA, TransportConstants.AOA_USB);

```

Comment (joeygrover) [reply android/sdl_android/src/main/java/com/smartdevicelink/transport/USBAccessoryAttachmentActivity.java:170]: Should avoid using an action string for an extra in an intent.

File: android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java [hunk 3]
```diff
@@ -1801,13 +1854,45 @@ public void onTransportConnected(final TransportRecord record) {
...
+            //Continuously Check for the BLUETOOTH_CONNECT Permission
+            btPermissionsRunnable = new Runnable() {
+                @Override
+                public void run() {
+                    if (!AndroidTools.isPermissionGranted(BLUETOOTH_CONNECT, SdlRouterService.this, SdlRouterService.this.getPackageName())) {
+                        btPermissionsHandler.postDelayed(btPermissionsRunnable, BT_PERMISSIONS_CHECK_FREQUENCY);
+                    } else {
+                        waitingForBTRuntimePermissions = false;
+                        initBluetoothSerialService();
+                    }
```
[the remark this answers is not in the document]
Comment (joeygrover) [reply android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java:1889]: We want to cancel the notification if the permission has been granted

File: android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java [hunk 4]
```diff
@@ -1256,10 +1277,14 @@ public int onStartCommand(Intent intent, int flags, int startId) {
                     (HashMap<String, Object>) intent.getSerializableExtra(TransportConstants.VEHICLE_INFO_EXTRA)
             );
         }
+        boolean isConnectedOverUSB = false;
+        if (intent != null && intent.hasExtra(TransportConstants.CONNECTION_TYPE_EXTRA)) {
+            isConnectedOverUSB = TransportConstants.ACTION_USB_ACCESSORY_ATTACHED.equalsIgnoreCase(intent.getStringExtra(TransportConstants.CONNECTION_TYPE_EXTRA));
```
Comment (joeygrover) [inline android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java:1282]:
```suggestion
            isConnectedOverUSB = TransportConstants.AOA_USB.equalsIgnoreCase(intent.getStringExtra(TransportConstants.CONNECTION_TYPE_EXTRA));
```

**Review by joeygrover — APPROVED** [review]
