### PR TITLE
Fix potential NPEs in BaseMenuManager

### LINKED ISSUE #1215: Issue when re-adding menu items (reloading UI)
### Bug Report
I am getting below error when running the app in Actual Ford Card Head Unit with Sync3. 

```
E/SdlProxy: 4.9.1: Result: INVALID_ID Info: null
 I/SdlProxy: 4.9.1: Finished sending main menu commands. Sending sub menu commands.
 I/SdlProxy: 4.9.1: RpcConverter Attempting to create com.smartdevicelink.proxy.rpc.AddCommandResponse
 E/SdlProxy: 4.9.1: Failed to send sub menu commands: null
 E/SdlProxy: 4.9.1: Error Sending Current Menu
 E/SdlProxy: 4.9.1: Failure handling protocol message: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
        at java.util.ArrayList.<init>(ArrayList.java:191)
        at com.smartdevicelink.managers.screen.menu.BaseMenuManager.setMenuCells(BaseMenuManager.java:177)
        at com.smartdevicelink.managers.screen.menu.MenuManager.setMenuCells(MenuManager.java:45)
        at com.smartdevicelink.managers.screen.menu.BaseMenuManager$8$1.onComplete(BaseMenuManager.java:953)
        at com.smartdevicelink.managers.screen.menu.BaseMenuManager$10.onError(BaseMenuManager.java:1054)
        at com.smartdevicelink.proxy.SdlProxyBase$92.onError(SdlProxyBase.java:4362)
        at com.smartdevicelink.proxy.SdlProxyBase.onRPCResponseReceived(SdlProxyBase.java:2230)
        at com.smartdevicelink.proxy.SdlProxyBase.handleRPCMessage(SdlProxyBase.java:2819)
        at com.smartdevicelink.proxy.SdlProxyBase.dispatchIncomingMessage(SdlProxyBase.java:1919)
        at com.smartdevicelink.proxy.SdlProxyBase.access$2700(SdlProxyBase.java:163)
        at com.smartdevicelink.proxy.SdlProxyBase$3.dispatch(SdlProxyBase.java:950)
        at com.smartdevicelink.proxy.SdlProxyBase$3.dispatch(SdlProxyBase.java:947)
        at com.smartdevicelink.Dispatcher.ProxyMessageDispatcher.handleMessages(ProxyMessageDispatcher.java:74)
        at com.smartdevicelink.Dispatcher.ProxyMessageDispatcher.access$000(ProxyMessageDispatcher.java:38)
        at com.smartdevicelink.Dispatcher.ProxyMessageDispatcher$1.run(ProxyMessageDispatcher.java:52)
        at java.lang.Thread.run(Thread.java:764)
```

The code that I use to reload UI is : 

```
private fun clearUI() {
        sdlManager?.screenManager?.apply {
            softButtonObjects = arrayListOf()
            menu = arrayListOf()
        }
        createUI()
    }
private fun createUI(){
  sdlManager?.screenManager.menu = menuCellList
  sdlManager?.screenManager?.softButtonObjects = mainButtonList
}
```

##### OS & Version Information
* Android Version: Samsung S9, Android  
* SDL Android Version: 4.9.1
* Testing Against: Ford Car with Sync

### PR DESCRIPTION
**Pull request by bilal-alsharifi**
Fixes #1215 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Try setting the menu to `null` and make sure the menu cells are getting cleared correctly without crashing the app:
```
sdlManager.getScreenManager().setMenu(null);
```

### Summary
This PR fixes some potential NPEs in `MenuManager` when setting the menu to `null` 

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java [hunk 1]
```diff
@@ -175,7 +175,11 @@ public void setMenuCells(@NonNull List<MenuCell> cells){
 		if (currentHMILevel == null || currentHMILevel.equals(HMILevel.HMI_NONE) || currentSystemContext.equals(SystemContext.SYSCTXT_MENU)){
 			// We are in NONE or the menu is in use, bail out of here
 			waitingOnHMIUpdate = true;
-			waitingUpdateMenuCells = new ArrayList<>(clonedCells);
+			if (clonedCells == null) {
```
Comment (joeygrover) [inline base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java]: Couldn't this be simplified like:
```
             waitingUpdateMenuCells = new ArrayList<>();
            if(clonedCells != null ){
                waitingUpdateMenuCells.addAll(clonedCells);
            }
```

Comment (bilal-alsharifi) [reply base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java]: Yes, that looks cleaner. I will update the PR.
