### PR TITLE
Fix Issue 1465 - NPE in ManagerUtility

### LINKED ISSUE #1465: NullPointerException While updating Image/Text after layout Change.
### Bug Report

SDL Application randomly crashes while I am trying to set Image/text after changing layout to `GRAPHIC_WITH_TEXT_AND_SOFTBUTTONS`. Same code was working before but just now I am getting following crash logs while trying to set image. The same is true for showing Text. If I dont change layout then app works as it is expected. I am using following code to change layout.

```java
 SetDisplayLayout setDisplayLayoutRequest = new SetDisplayLayout();
        setDisplayLayoutRequest.setDisplayLayout(PredefinedLayout.GRAPHIC_WITH_TEXT_AND_SOFTBUTTONS.toString());
        setDisplayLayoutRequest.setOnRPCResponseListener(new OnRPCResponseListener() {
            @Override
            public void onResponse(int correlationId, RPCResponse response) {
                if (((SetDisplayLayoutResponse) response).getSuccess()) {
                    Log.i("SdlService", "Display layout set successfully.");
                    updateSoftButton("Alert","Activity");
                    // Proceed with more user interface RPCs
                } else {
                    Log.i("SdlService", "Display layout request rejected.");
                }
            }

            @Override
            public void onError(int correlationId, Result resultCode, String info){
                Log.e(TAG, "onError: "+ resultCode+ " | Info: "+ info );
            }
        });
```

Crash Log.

```
2020-08-25 08:57:48.216 10832-10832/com.ford.research.BioSD E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ford.research.BioSD, PID: 10832
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Enum.ordinal()' on a null object reference
        at com.smartdevicelink.managers.ManagerUtility$WindowCapabilityUtility.getMaxNumberOfMainFieldLines(ManagerUtility.java:77)
        at com.smartdevicelink.managers.screen.BaseTextAndGraphicManager.assembleShowText(BaseTextAndGraphicManager.java:412)
        at com.smartdevicelink.managers.screen.BaseTextAndGraphicManager.sdlUpdate(BaseTextAndGraphicManager.java:259)
        at com.smartdevicelink.managers.screen.BaseTextAndGraphicManager.update(BaseTextAndGraphicManager.java:219)
        at com.smartdevicelink.managers.screen.BaseScreenManager.commit(BaseScreenManager.java:579)
        at com.smartdevicelink.managers.screen.ScreenManager.commit(ScreenManager.java:45)
        at com.ford.research.BioSD.SdlService.isSafeToShowAlert(SdlService.java:621)
        at com.ford.research.BioSD.SdlService$10.run(SdlService.java:770)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6780)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1500)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1390)
```

##### Reproduction Steps

1.  Set layout to `GRAPHIC_WITH_TEXT_AND_SOFTBUTTONS`
2.  Change Text/Image

##### Expected Behavior

Update vehicle HMI with new Image or text

##### Observed Behavior

App crashes while trying to set image or text. After layout change.

##### OS & Version Information

*   Android Version: 7.0
*   SDL Android Version: 4.12.0
*   Testing Against: Ford SYNC 3.3 Build 18266

##### Test Case, Sample Code, and / or Example App

Change image.

```java
sdlManager.getScreenManager().beginTransaction();
sdlArtwork = new SdlArtwork(SDL_RED_IMAGE_FILENAME, FileType.GRAPHIC_JPEG, R.drawable.red, true);
sdlManager.getScreenManager().setPrimaryGraphic(sdlArtwork);
sdlManager.getScreenManager().commit(new CompletionListener() {
    @Override
    public void onComplete(boolean success) {
        Log.i(TAG, "ScreenManager update complete: " + success);
    }
});
```

Show Text

```java
sdlManager.getScreenManager().beginTransaction();
sdlManager.getScreenManager().setTextField1(text1);
sdlManager.getScreenManager().setTextField2(text2);
sdlManager.getScreenManager().setTextField3(text3);
sdlManager.getScreenManager().commit(new CompletionListener() {
    @Override
    public void onComplete(boolean success) {
        Log.i(TAG, "ScreenManager update complete: " + success);
    }
});
```

### PR DESCRIPTION
**Pull request by joeygrover**
Fixes #1465 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android, Java SE, and Java EE

#### Unit Tests
- Added unit tests around the utility classes that were modified

### Summary
Added null checks to a couple methods in the `ManagerUtility` class that iterates over lists. While there was a null check for the list itself, it skipped such check on the items stored in the list.

##### Bug Fixes
* Check for null in multiple cases now since null is a valid item in a list

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/ManagerUtilityTests.java [hunk 1]
```diff
@@ -0,0 +1,206 @@
...
+		capability.setTextFields(singleLineList);
+		maxNumerOfLines = ManagerUtility.WindowCapabilityUtility.getMaxNumberOfMainFieldLines(capability);
+		assertEquals(4, maxNumerOfLines);
+
+		List<TextField> nullList = new ArrayList<>();
+		nullList.add(null);
+		assertNotNull(nullList);
+		capability.setTextFields(nullList);
+		assertNotNull(capability);
+		assertNotNull(capability.getTextFields()); //Fails
```
Comment (bilal-alsharifi) [inline android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/ManagerUtilityTests.java:192]: This passes after the fix, right? can we remove the comment if it is not relevant anymore?
