### PR TITLE
Fix OnButtonPress's CustomButtonID getter/setter naming

### LINKED ISSUE #547: The name of setter and getter in OnButtonPress are ambiguous
In the class com.smartdevicelink.proxy.rpc.OnButtonPress

Actual: setCustomButtonName/getCustomButtonName

Expected: setCustomButtonID/getCustomButtonID

### PR DESCRIPTION
**Pull request by bilal-alsharifi**
Fixes #547

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

#### Unit Tests
Updated corresponding `OnButtonPress` tests.

### Summary
This PR updates the names of `setCustomButtonName()` & `getCustomButtonName()` in `OnButtonPress` to match the RPC spec.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: base/src/main/java/com/smartdevicelink/proxy/rpc/OnButtonPress.java [hunk 1]
```diff
@@ -179,10 +179,37 @@ public ButtonPressMode getButtonPressMode() {
...
         setParameters(KEY_BUTTON_PRESS_MODE, buttonPressMode);
     }
+
+    @Deprecated
+    /**
+    * @deprecated use {@link #setCustomButtonID(Integer)} ()} instead.
+    */
     public void setCustomButtonName(Integer customButtonID) {
         setParameters(KEY_CUSTOM_BUTTON_ID, customButtonID);
     }
```
Comment (RHenigan) [inline base/src/main/java/com/smartdevicelink/proxy/rpc/OnButtonPress.java:189]: Do we want a new line here?

Comment (RHenigan) [reply base/src/main/java/com/smartdevicelink/proxy/rpc/OnButtonPress.java:189]: added
