### PR TITLE
Prevent potential npe on resolution

### LINKED ISSUE #1611: Potential NullPointerException in VideoStreamingParameters.update
### Bug Report
In the `VideoStreamingParameters.update` methods we try to set the resolution height and width without checking if `VideoStreamingParameters.resolution` is null which can lead to a potential NPE.

### PR DESCRIPTION
**Pull request by RHenigan**
Fixes #1611 

This PR is **[ready]** for review.

### Risk
This PR makes **[no]** API changes.

### Testing Plan
- [X] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [X] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android, Java SE, and Java EE

### Summary
VideoStreamingParameters.update will now set a default value for resolution if it was null before trying to assign a new resolutionHeight or resolutionWidth

##### Bug Fixes
This will prevent the update method from trying to call setResolutionHeight or setResolutionWidth on a nullObjectReference

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: base/src/main/java/com/smartdevicelink/streaming/video/VideoStreamingParameters.java [hunk 1]
```diff
@@ -119,6 +119,11 @@ public void update(VideoStreamingParameters params) {
                 this.interval = params.interval;
             }
             if (params.resolution != null) {
+                if (this.resolution == null) {
+                    this.resolution = new ImageResolution();
+                    resolution.setResolutionWidth(DEFAULT_WIDTH);
+                    resolution.setResolutionHeight(DEFAULT_HEIGHT);
```
Comment (bilal-alsharifi) [inline base/src/main/java/com/smartdevicelink/streaming/video/VideoStreamingParameters.java:125]:
```suggestion
                    this.resolution = new ImageResolution(DEFAULT_WIDTH, DEFAULT_HEIGHT);
```

File: base/src/main/java/com/smartdevicelink/streaming/video/VideoStreamingParameters.java [hunk 2]
```diff
@@ -152,6 +157,12 @@ public void update(VideoStreamingCapability capability, String vehicleMake) {
         ImageResolution resolution = capability.getPreferredResolution();
         if (resolution != null) {
 
+            if (this.resolution == null) {
+                this.resolution = new ImageResolution();
+                resolution.setResolutionWidth(DEFAULT_WIDTH);
+                resolution.setResolutionHeight(DEFAULT_HEIGHT);
```
Comment (bilal-alsharifi) [inline base/src/main/java/com/smartdevicelink/streaming/video/VideoStreamingParameters.java:163]:
```suggestion
                this.resolution = new ImageResolution(DEFAULT_WIDTH, DEFAULT_HEIGHT);
```

**Review by bilal-alsharifi — CHANGES_REQUESTED** [review]

**Review by bilal-alsharifi — APPROVED** [review]
