### PR TITLE
Fix Main Menu UI updates do not take text field name into account

### LINKED ISSUE #1628: Main Menu UI Updates Don't Take TextFieldName / ImageFieldName into account
### Bug Report
When uploading a `MenuCell`, we need to check `menuCommandSecondaryText`, `menuCommandTertiaryText`, `menuSubMenuSecondaryText`, `menuSubMenuTertiaryText`, `menuCommandSecondaryImage`, and `menuSubMenuSecondaryImage`

##### Reproduction Steps
1. Connect to a head unit that doesn't support secondary text, tertiary text, or secondary image.
2. Attempt to send a menu cell with secondary text, tertiary text, or secondary image.

##### Expected Behavior
The unsupported text and image are not sent / uploaded.

##### Observed Behavior
The unsupported text and image are sent / uploaded.

##### OS & Version Information
* Android Version: n/a
* SDL Android Version: n/a
* Testing Against: n/a

##### Test Case, Sample Code, and / or Example App
n/a

### PR DESCRIPTION
**Pull request by RHenigan**
Fixes #1628

This PR is **[ready]** for review.

### Risk
This PR makes **[no]** API changes.

### Testing Plan
- [X] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [X] I have run the unit tests with this PR
- [X] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [X] I have tested Android, Java SE, and Java EE

#### Unit Tests
N/A

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: N/A

### Summary
 Add new checks menuCommandSecondaryText, menuCommandTertiaryText, menuSubMenuSecondaryText, and menuSubMenuTertiaryText

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java [hunk 1]
```diff
@@ -959,11 +996,16 @@ private void transferIdsToKeptSubCells(List<MenuCell> old, List<MenuCell> keeps)
         return builtCommands;
     }
 
+    // An individual AddCommand RPC for a given MenuCell
+    // @param cell The cell to create the RPC for
+    // @param shouldHaveArtwork Whether artwork should be applied to the RPC
+    // @param position The position the AddCommand RPC should be given
+    // @returns The AddCommand RPC
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java:1003]:
```suggestion
    /**
     * An individual AddCommand RPC for a given MenuCell
     *
     * @param cell              MenuCell to create RPCs for
     * @param shouldHaveArtwork Boolean that indicates whether artwork should be applied to the RPC or not
     * @param position          The position the AddCommand RPC should be given
     * @return The AddCommand RPC
     */
```

File: base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java [hunk 2]
```diff
@@ -980,10 +1022,15 @@ private AddCommand commandForMenuCell(MenuCell cell, boolean shouldHaveArtwork,
         return command;
     }
 
+    // An individual AddSubMenu RPC for a given MenuCell
+    // @param cell The cell to create the RPC for
+    // @param shouldHaveArtwork Whether artwork should be applied to the RPC
+    // @param position The position the AddSubMenu RPC should be given
+    // @returns The AddSubMenu RPC
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java:1029]:
```suggestion
    /**
     * An individual AddSubMenu RPC for a given MenuCell
     *
     * @param cell              The cell to create the RPC for
     * @param shouldHaveArtwork Whether artwork should be applied to the RPC
     * @param position          The position the AddSubMenu RPC should be given
     * @return The AddSubMenu RPC
     */
```

File: base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java [hunk 3]
```diff
@@ -997,6 +1044,10 @@ private AddSubMenu subMenuCommandForMenuCell(MenuCell cell, boolean shouldHaveAr
 
     // CELL COMMAND HANDLING
 
+    // Call a listener for a currently displayed MenuCell based on the incoming OnCommand notification
+    // @param cells The menu cells to check (including their subcells)
+    // @param command The notification retrieved
+    // @returns True if the handler was found, false if it was not found
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java:1050]:
```suggestion
    /**
     * Call a listener for a currently displayed MenuCell based on the incoming OnCommand notification
     *
     * @param cells   ArrayList of MenuCell's to check (including their subcells)
     * @param command OnCommand notification retrieved
     * @return True if the handler was found, false if it was not found
     */
```

File: base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java [hunk 4]
```diff
@@ -1379,12 +1430,11 @@ private void addUniqueNamesToCells(List<MenuCell> cells) {
...
-    /**
-     Check for cell lists with completely duplicate information, or any duplicate voiceCommands
 
-     @param cells The cells you will be adding
-     @return Boolean that indicates whether menuCells are unique or not
-     */
+    //Check for cell lists with completely duplicate information, or any duplicate voiceCommands
+    //
+    //@param cells The cells you will be adding
+    //@return Boolean that indicates whether menuCells are unique or not
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java:1437]:
```suggestion
    /**
     * Check for cell lists with completely duplicate information, or any duplicate voiceCommands
     *
     * @param cells            ArrayList of MenuCell's you will be adding
     * @param allVoiceCommands ArrayList of String's for VoiceCommands
     * @return Boolean that indicates whether menuCells are unique or not
     */
```

File: base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java [hunk 5]
```diff
@@ -784,8 +797,8 @@ private boolean shouldRPCsIncludeImages(List<MenuCell> cells) {
                 if (secondaryArtwork != null && !secondaryArtwork.isStaticIcon() && fileManager.get() != null && !fileManager.get().hasUploadedFile(secondaryArtwork)) {
                     return false;
                 }
-            } else if (cell.getSubCells() != null && cell.getSubCells().size() > 0) {
-                return shouldRPCsIncludeImages(cell.getSubCells());
+            } else if (cell.getSubCells() != null && cell.getSubCells().size() > 0 && ! shouldRPCsIncludeImages(cell.getSubCells())) {
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java:800]:
```suggestion
            } else if (cell.getSubCells() != null && cell.getSubCells().size() > 0 && !shouldRPCsIncludeImages(cell.getSubCells())) {
```

**Review by JulianKast — CHANGES_REQUESTED** [review]
