### PR TITLE
Update LCM to workaround Sync 3 bug with media capabilities 

### LINKED ISSUE #1690: Primary Graphic not sent to SDL Core for Media Template
### Bug Report
Primary Graphic and text updated using Screen Manager, however only text gets updated

##### Reproduction Steps
- Connect a media app, it will start on the media template
- Change the layout to something else, like textAndGraphic
- Change the layout back to MEDIA
- Try to show another image.
- The display capabilities that are returned don’t include that the primary graphic is supported, so it will fail.

##### Expected Behavior
Text and graphic should be updated

##### Observed Behavior
Only text is updated. Screen manager somehow determines that there is no image to update.

##### OS & Version Information
SDL Java Suite Version: 5.1.1
Testing Against: Ford SYNC 3.0

### PR DESCRIPTION
**Pull request by bilal-alsharifi**
Fixes #1690

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android

#### Unit Tests
Added unit tests to test the workaround logic 

#### Core Tests
On Sync 3.0:

1. Connect a media app, it will start on the media template
2. Change the layout to something else, like textAndGraphic
3. Change the layout back to MEDIA
4. Try to show another image and confirm it appears 

Core version / branch / commit hash / module tested against: 7.1.1
HMI name / version / branch / commit hash / module tested against: Generic HMI 0.10.0

### Summary
This PR updates the `LifecycleManager` to replace the incorrect capabilities that are included in the `SetDisplayLayoutResponse` for MEDIA apps with the ones from `RegisterAppInterfaceResponse` as a workaround to fix a bug in SYNC3.

#### Bug Fixes
Workaround for a Ford Sync 3 bug where doing `SetDisplayLayout` to the MEDIA template would result in incorrect display capabilities being returned that claim the primaryGraphic is not supported.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java [hunk 1]
```diff
@@ -405,6 +411,10 @@ public void onReceived(RPCMessage message) {
                             //If the vehicle is acceptable and this is the first check, init security lib
                             setSecurityLibraryIfAvailable(vehicleType);
                         }
+                        // HAX: Issue #1690, Ford Sync bug returning incorrect display capabilities (https://github.com/smartdevicelink/sdl_java_suite/issues/1690). Store the initial capabilities if we are a media app so that we can use them in the future.
+                        if (appConfig.appType.contains(AppHMIType.MEDIA)) {
+                            initialMediaCapabilities = raiResponse.getDisplayCapabilities();
```
Comment (JulianKast) [inline base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java:416]: is RegisterAppInterfaceResponse. getDisplayCapabilities deprecated because we don't want it to be public anymore?

**Review by JulianKast — APPROVED** [review]
