### PR TITLE
Fix description for `SeatControlCapabilities` and `RadioControlCapabilities`

### LINKED ISSUE #1739: Fix description for `SeatControlCapabilities` and `RadioControlCapabilities`
### Bug Report
Fix description for `SeatControlCapabilities` and `RadioControlCapabilities` as they were fixed in the RPC_Spec

### PR DESCRIPTION
**Pull request by JulianKast**
Fixes #1739 

This PR is **[ready]** for review.

### Risk
This PR makes **[no]** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android, Java SE, and Java EE

#### Unit Tests
n/a

#### Core Tests
n/a

### Summary
Fix description for `SeatControlCapabilities` and `RadioControlCapabilities` per RPC spec 8.0.0 PR: :https://github.com/smartdevicelink/rpc_spec/pull/319

##### Bug Fixes
* Fix description for `SeatControlCapabilities` and `RadioControlCapabilities` per RPC spec 8.0.0

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: base/src/main/java/com/smartdevicelink/proxy/rpc/RadioControlCapabilities.java [hunk 1]
```diff
@@ -79,7 +79,7 @@ public RadioControlCapabilities(@NonNull String moduleName) {
     /**
```
Comment (bilal-alsharifi) [inline base/src/main/java/com/smartdevicelink/proxy/rpc/RadioControlCapabilities.java:79]: The constructor seems to have a similar issue in the Javadoc as well

File: base/src/main/java/com/smartdevicelink/proxy/rpc/SeatControlCapabilities.java [hunk 2]
```diff
@@ -94,7 +94,7 @@ public String getModuleName() {
     /**
```
Comment (bilal-alsharifi) [inline base/src/main/java/com/smartdevicelink/proxy/rpc/SeatControlCapabilities.java:94]: The constructor seems to have a similar issue in the Javadoc as well

File: base/src/main/java/com/smartdevicelink/proxy/rpc/SeatControlCapabilities.java [hunk 3]
```diff
@@ -94,7 +94,7 @@ public String getModuleName() {
...
      * Sets the moduleName portion of the SeatControlCapabilities class
      *
-     * @param moduleName -  The short friendly name of the light control module. It should not be used to identify a module by mobile application.
+     * @param moduleName -  The short friendly name of the seat control module. It should not be used to identify a module by mobile application.
      */
     public SeatControlCapabilities setModuleName(@NonNull String moduleName) {
```
Comment (bilal-alsharifi) [inline base/src/main/java/com/smartdevicelink/proxy/rpc/SeatControlCapabilities.java:99]: Also, `AudioControlCapabilities` class seem to have similar typos in the Javadoc

**Review by bilal-alsharifi — COMMENTED** [review]
Found more places were we have similar typos

**Review by bilal-alsharifi — APPROVED** [review]
