### PR TITLE
Deprecate mediaClock

### LINKED ISSUE #1606: Deprecate Media Clock according to Rpc Spec changes
### Bug Report
Deprecate Media Clock according to Rpc Spec changes https://github.com/smartdevicelink/rpc_spec/pull/309

### PR DESCRIPTION
**Pull request by JulianKast**
Fixes #1606 

This PR is **[ready]** for review.

### Risk
This PR makes **[no]** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android, Java SE, and Java EE

#### Unit Tests
n/a

#### Core Tests
n/a

### Summary
Deprecated MediaClock in Show.java and TextFieldName.java according to rpc spec changes https://github.com/smartdevicelink/rpc_spec/pull/309
##### Enhancements
* Deprecated MediaClock in Show.java and TextFieldName.java

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: base/src/main/java/com/smartdevicelink/proxy/rpc/Show.java [hunk 1]
```diff
@@ -117,11 +117,14 @@
...
  *                 <td>N</td>
- * 			<td><p>Must be properly formatted as described in the MediaClockFormat enumeration. </p><p>If a value of five spaces is provided, this will clear that field on the display (i.e. the media clock timer field will not display anything) </p>Maxlength = 500</td>
- * 			<td>SmartDeviceLink 1.0</td>
- * 		</tr>
+ * 			<td>{"string_min_length": 0, "string_max_length": 500}</td>
+ * 			<td>
+ *             @since SmartDeviceLink 1.0.0
+ *             @deprecated in SmartDeviceLink 7.1.0
+ * 			</td>
+ *  </tr>
```
Comment (RHenigan) [inline base/src/main/java/com/smartdevicelink/proxy/rpc/Show.java:127]: can this </tr> tag be indented to align with the formatting?

**Review by RHenigan — APPROVED** [review]
