### PR TITLE
Correct Lockscreen start behavior

### LINKED ISSUE #1515: LockScreen behavior is incorrect for Display Always and Dismissible
### Bug Report
When `LockScreenConfig` `DisplayMode` is set to `DISPLAY_MODE_ALWAYS` and `enableDismissGesture` is set to true there is an issue with how the lock screens are being displayed and dismissed.

Part 1
##### Reproduction Steps
1. Create a new `LockScreenConfig` and set `DisplayMode` to `DISPLAY_MODE_ALWAYS` and set `enableDismissGesture` to true
2. Make sure DD is off on Core or Manticore and then connect the app to Core or Manticore

##### Expected Behavior
A Dismissible lockScreen should appear

##### Observed Behavior
A lockScreen that is not dismissible is presented

Part 2
##### Reproduction Steps
1.  Continue from part 1 and set DD to ON in Core or Manticore
2. The LockScreen should change and now be dismissible
3. Dismiss the lockscreen

##### Expected Behavior
The LockScreen should be dismissed and the user should be able to interact with the application

##### Observed Behavior
The LockScreen is dismissed but there is another LockScreen presented that the user cannot dismiss

##### Test Case, Sample Code, and / or Example App
Set in SdlService:
`LockScreenConfig lockScreenConfig = new LockScreenConfig();` `lockScreenConfig.setDisplayMode(LockScreenConfig.DISPLAY_MODE_ALWAYS);`
 `lockScreenConfig.enableDismissGesture(true);`
 `builder.setLockScreenConfig(lockScreenConfig);`

### PR DESCRIPTION
**Pull request by joeygrover**
Fixes #1515  

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android

#### Core Tests (Manticore)

Create app with Lockscreen config:

```java
LockScreenConfig lockScreenConfig = new LockScreenConfig();
lockScreenConfig.setDisplayMode(LockScreenConfig.DISPLAY_MODE_ALWAYS);
lockScreenConfig.enableDismissGesture(true);
```

Test 1:

1. Ensure DriverDistraction is OFF on Manticore
2. Deploy app
3. Notice the lockscreen appears
4. Enable DriverDistraction on Manticore
5. Notice there is now the option to swipe away lockscreen
6. Swipe away lockscreen
7. Notice no lockscreen is displayed
8. Turn OFF DriverDistraction on Manticore
9. Notice no lockscreen is displayed

Test 2:

1. Ensure DriverDistraction is ON on Manticore
2. Deploy app
3. Notice the lockscreen appears with option to swipe away
4. Swipe away lockscreen
5. Notice no lockscreen is displayed
6. Turn off DriverDistraction on Manticore
7. Notice no lockscreen is displayed

Test 3:

1. Ensure DriverDistraction is OFF on Core
2. Deploy app
3. Notice the lockscreen appears
4. Enable DriverDistraction on Core with `lockScreenDismissalEnabled= true`
5. Notice there is now the option to swipe away lockscreen
6. Turn OFF DriverDistraction on Core
7. Notice lockscreen is still viewable
8. Enable DriverDistraction on Core with `lockScreenDismissalEnabled= false`
9. Notice there is no longer an option to swipe away lockscreen and swiping does not dismiss lockscreen
10. Repeat steps 4-6

### Summary
- Added a check to prevent multiple startActivity calls with the same intent. There is a race condition when starting an app that instantly connects with Core that causes this.
- Added a delay for a known (second call" to start the lockscreen activity. This is due to the calls to start the activity being too close and the system will simply queue up the intent and restart the activity right after it finishes.
- Refactored logic in lockscreen activity and DD handling to allow updating of lockscreen properly past initial launch.
- Refactored some methods and variables to better adhere to coding style and more descriptive naming.

##### Bug Fixes
* Prevents a duplication startActivity call and therefore the lockscreen is not displayed again after dismissal
* Fix issue where dismissible state goes from Enabled to Disabled

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/LockScreenManager.java [hunk 1]
```diff
@@ -195,34 +198,54 @@ public void onNotified(RPCNotification notification) {
...
-                            if (!receivedFirstDDNotification && displayMode == LockScreenConfig.DISPLAY_MODE_ALWAYS) {
-                                launchLockScreenActivity();
+                    synchronized (this) {
+                        OnDriverDistraction ddState = (OnDriverDistraction) notification;
+                        driverDistStatus = DriverDistractionState.DD_ON.equals(ddState.getState());
+                        mLockscreenWarningMsg = ddState.getLockscreenWarningMessage();
+                        boolean previousDismissibleState = isLockscreenDismissible;
+                        if(ddState.getLockscreenDismissibility() == null ) {
+                            isLockscreenDismissible = ddState.getLockscreenDismissibility();
+                        } //If the param is null, we assume it stays as the previous value
```
Comment (RHenigan) [inline android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/LockScreenManager.java:208]: @joeygrover The comment and the logic are mismatched here.

should this be:
```
if(ddState.getLockscreenDismissibility() == null ) {
    isLockscreenDismissible = previousDismissibleState;
} else {
    isLockscreenDismissible = ddState.getLockscreenDismissibility();
}
```

**Review by RHenigan — APPROVED** [review]
