### PR TITLE
Fix some potential NPEs in SystemCapabilityManager

### LINKED ISSUE #1221: If null throw null pointer...
https://github.com/smartdevicelink/sdl_java_suite/blob/93778656113f0023ec7025281b77e28000a1f5bd/base/src/main/java/com/smartdevicelink/proxy/SystemCapabilityManager.java#L105

### PR DESCRIPTION
**Pull request by bilal-alsharifi**
Fixes #1221 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
This PR fixes some potential NPEs in SystemCapabilityManager

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: base/src/main/java/com/smartdevicelink/proxy/SystemCapabilityManager.java [hunk 1]
```diff
@@ -290,7 +296,9 @@ public void onReceived(RPCMessage message) {
                                                     List<AppServiceCapability> appServicesCapabilitiesList = appServicesCapabilities.getAppServices();
                                                     AppServicesCapabilities cachedAppServicesCapabilities = (AppServicesCapabilities) cachedSystemCapabilities.get(systemCapabilityType);
                                                     //Update the cached app services
-                                                    cachedAppServicesCapabilities.updateAppServices(appServicesCapabilitiesList);
+													if (cachedAppServicesCapabilities != null) {
+														cachedAppServicesCapabilities.updateAppServices(appServicesCapabilitiesList);
+													}
```
Comment (joeygrover) [inline base/src/main/java/com/smartdevicelink/proxy/SystemCapabilityManager.java]: Spacing seems to be off here.
