### PR TITLE
Deprecate APIs to prepare for next major release

### LINKED ISSUE #1362: Classes that need to be removed in next major release should be deprecated
### Bug Report
Some classes like `ProxyBridge`, `IProxyListener`, and some other `SdlProxyBase` callbacks will be removed in the next major release as part of using `LifecycleManager` to replace`SdlProxyBase`. These classes should be deprecated before they are being removed in the next major release.

### PR DESCRIPTION
**Pull request by bilal-alsharifi**
Fixes #1362 

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android, Java SE, and Java EE

#### Unit Tests
Unit tests should not be affected

### Summary
This PR deprecates some public APIs to prepare for removing them in the next major version change

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: base/src/main/java/com/smartdevicelink/proxy/interfaces/ISdl.java [hunk 1]
```diff
@@ -147,8 +150,16 @@
      * @param rpcs List of RPC requests
      * @param listener OnMultipleRequestListener that is called between requests and after all are processed
      */
+    @Deprecated
     void sendRequests(List<? extends RPCRequest> rpcs, final OnMultipleRequestListener listener);
 
+    /**
+     * Pass a list of RPC requests through the proxy to be sent to core
+     * @param rpcs List of RPC requests
```
Comment (RHenigan) [inline base/src/main/java/com/smartdevicelink/proxy/interfaces/ISdl.java:158]:
```suggestion
     * Pass a list of RPC messages through the proxy to be sent to core
     * @param rpcs List of RPC messages
```
